### ISSUE TITLE
Report not Work

### ISSUE THREAD

**Issue by xenovoid0914** [UnifierHQ/unifier#112]
**Checklist**

- [ ] The same issue was not reported yet.
- [ ] This is not a report against a user of the official instance.
- [ ] All info applicable to the issue has been attached.

**Describe the bug**
Tittle

**To Reproduce**

**Expected behavior**

**Screenshots**
![螢幕擷取畫面 2024-05-02 200203](https://github.com/UnifierHQ/unifier/assets/168738572/d8dfc3fc-f333-4481-817e-86298a3c666a)

**Platform**

**Version**

**Extensions**

**Modified instance repository**
![螢幕擷取畫面 2024-05-02 200203](https://github.com/UnifierHQ/unifier/assets/168738572/dd451609-e11a-4f1a-8177-fe3fbcfc0fcd)

**Additional context**
no

**Comment by NullyIsHere** [comment]
Please translate to english.

**Comment by NullyIsHere** [comment]
Its the @ no uppercase.

**Comment by greeeen-dev** [comment]
If it still doesn't work, your instance configuration is incorrect. You need to provide valid IDs for your home server, moderator role, report channel and logging channel.
