### ISSUE TITLE
Buffed anti-raid

### ISSUE THREAD

**Issue by greeeen-dev** [UnifierHQ/unifier#114]
**Checklist**

- [X] The same feedback was not posted yet.
- [X] This is not a suggestion for the moderation team.
- [X] All info applicable to the issue has been attached.

**Is your feature request related to a problem? Please describe.**

Anti-raid is currently limited to invites only. This should be extended to include all types of content that may be harmful.

**Describe the solution you'd like**

Add a new anti-raid system based on the current one we have

**Describe alternatives you've considered**

**Additional context**

# Release ASAP as v1.2.2-patch2. No delaying, once it's ready and working WITHOUT ISSUES get it out there.
This is in response to raid threats from May 7th. We will not tolerate this, and we will put all our resources towards preventing whatever they may throw at us.

Also consider releasing it as part of v1.1.15 as they both use Bridge v2, so it should be compatible.

**Comment by NullyIsHere** [comment]
Things that might be harmful
Messages > 100 chars, less or more
A message with > 5 emojis
A whitelist for using more than two ## before message.

**Comment by greeeen-dev** [comment]
For header texts (# h1, ## h2, etc), we'll multiply the character count by a certain value, might help.
