### ISSUE TITLE
Create threads for reviewing reports

### ISSUE THREAD

**Issue by HypedIgnis** [UnifierHQ/unifier#122]
**Checklist**

- [x] The same feedback was not posted yet.
- [x] This is not a suggestion for the moderation team.
- [x] All info applicable to the issue has been attached.

**Is your feature request related to a problem? Please describe.**
Yes. Moderation Reports for moderators do not create a designated discussion space, so all reports and discussions regarding them are messily packed in a single channel.

**Describe the solution you'd like**
Threads to be automatically added to reports.
When a report get through to our reports channel, I would like the bot to automatically open a thread for discussion regarding said report. This would allow more organized and **unified** discussions for our moderators.

**Describe alternatives you've considered**

**Additional context**

**Comment by greeeen-dev** [comment]
Will work on this for v1.2.4
