### ISSUE TITLE
Threads support

### ISSUE THREAD

**Issue by greeeen-dev** [UnifierHQ/unifier#133]
**Checklist**

- [X] The same feedback was not posted yet.
- [X] This is not a suggestion for the moderation team.
- [X] All info applicable to the issue has been attached.

**Is your feature request related to a problem? Please describe.**

Currently, threads are not supported, and sending messages in a thread of a Unifier linked channel will throw an error.

**Describe the solution you'd like**

Add support for threads.

**Describe alternatives you've considered**

**Additional context**

**Comment by greeeen-dev** [comment]
Someone remind me tomorrow that I have to learn how threads work with Nextcord

**Comment by greeeen-dev** [comment]
Pushing this back to v2.0.1, gotta learn how threads work on Nextcord first

**Comment by greeeen-dev** [comment]
Just realized something...

A lot of services, like Revolt, don't support Threads, while services like Guilded do support it but Webhooks don't like Threads for some reason (tbh, what did I expect, Guilded API is a pain in the ass to work with. Kudos to Revolt for making their API easy as hell to work with, Masquerade is a godsend). Because of this feature disparity between the platforms, I'm not sure if it'd be worth trying to implement Threads support, as people won't be able to receive or send messages from Threads.

@NullyIsHere thoughts?

**Comment by greeeen-dev** [comment]
Closing - Nextcord doesn't support editing webhook messages in Threads apparently

**Comment by CrimsonFork** [comment]
It seems this shortcoming has been addressed a couple months later. https://github.com/nextcord/nextcord/pull/1160
> A lot of services […] don't support Threads

Something We've seen a couple Matrix clients do is display threaded messages in a similar manner to a reply to the initial thread message in the main timeline, almost like a label for E-Mails, it works pretty well, personally We actually kinda wish that's how Discord handled it, as threads get so easily lost. Anyway, something like this could be a way to at least have some function of the threads be carried over.

Alternatively the bridge could maybe automatically create a separate channel to mirror just the thread. Or, failing all of those, at least have an option to just manually bind a thread to a Unifier room.
