### ISSUE TITLE
Safemode not accessible in some cases.

### ISSUE THREAD

**Issue by NullyIsHere** [UnifierHQ/unifier#173]
### Checklist

- [X] The same feedback was not posted yet.
- [X] This is not a suggestion for the moderation team.
- [X] All info applicable to the issue has been attached.

### Problem

In hosts that use Pterodactyl, or any panel to be realistic. You normally **cant** modify the start command, only the .py to launch, therefore its not easy to enable safemode.

### Proposed solution

Now that we have a bootloader, we could modify restart command like so:
u!restart - Normal Restart
u!restart safemode - Restarts with safemode

### Alternatives considered

You could technically put in the python file like this "unifier.py safemode". But some host prohibit + can trigger anti abuse systems.

### Additional context

_Didnt put any label because ita not technically a bug._

**Comment by greeeen-dev** [comment]
*submits a bug report*

"Didnt put any label because ita not technically a bug."

what

(on a serious note, i will fix this after my math exam)

**Comment by Arhznblaster** [comment]
i'll make a half fix wait

**Comment by Arhznblaster** [comment]
nvm im also busy lol

**Comment by greeeen-dev** [comment]
working on it now

**Comment by greeeen-dev** [comment]
should be fixed in https://github.com/UnifierHQ/unifier/commit/70c10f4a61b6e932a1e2b6427cd178daf05c9a01
