### ISSUE TITLE
[Feat] Use slash instead of text commands

### ISSUE THREAD

**Issue by greeeen-dev** [UnifierHQ/unifier#180]
### Checklist

- [X] The same feedback was not posted yet.
- [X] This is not a suggestion for the moderation team.
- [X] All info applicable to the issue has been attached.

### Problem

Currently, all Unifier commands use text-based commands rather than the new slash commands. When we create our public instance, it should use slash commands instead of text commands.

Well, technically, [we don't really have to do this since Unifier requires message content access as part of its core functionality](https://support-dev.discord.com/hc/en-us/articles/6027634717335-I-Received-the-Message-Content-Intent-for-Other-Functionality-Can-I-Use-Prefix-Commands), but it's not good practice, and we do run the risk of getting our privileged intents application denied.

### Proposed solution

All user and moderator commands should be converted to slash commands. System management commands (such as `u!load`, `u!restart`, etc.) should remain as legacy text commands, so that only bot owners can see these commands.

### Alternatives considered

Making system management commands a part of user installation commands have been considered, but we would like to learn how exactly this can be implemented before we do this.

### Additional context

Making Unifier go slash was a popular topic of debate, especially among the dev team. While I initially opposed using slash commands because they just created unnecessary latency, I came to accept this change as we grew and broadened our mission.

As much as we hate slash commands for how slow and unresponsive they are (common Discord Webhooks L, don't ask us how Unifier can still achieve insane speeds with them), we need to embrace this change, especially since we're going to be making a public instance very soon and we can't really keep using text commands on verified bots.

We will be releasing slash commands as part of 3.5.0, instead of 4.0.0. Thanks to Nextcord, this doesn't involve heavy rewriting that'd cause breaking changes, so we don't need to release a major update for this change.

**Comment by NullyIsHere** [comment]
#179
