### ISSUE TITLE
Alllow to delete "Identify" message from the channels.

### ISSUE THREAD

**Issue by NullyIsHere** [UnifierHQ/unifier#181]
### Checklist

- [X] The same feedback was not posted yet.
- [X] This is not a suggestion for the moderation team.
- [X] All info applicable to the issue has been attached.

### Problem

I dont like when i Identify a button the message that Unifier sends cannot be deleted, occupying space in the chatroom.

### Proposed solution

My best idea is a button "Delete" that allows the user that used Identify, or mods, admins or owners of a instance to delete the message.

### Alternatives considered

A like timer that in 10 minutes expires and gets deleted, in this case a "Keep" button for saving for example logs of a raid would be a good addition.

**Comment by NullyIsHere** [comment]
## New alternative:
Converting it to ephemeral, but that prevents staff from seeing it

**Comment by greeeen-dev** [comment]
I'd rather keep these two separate.
