### ISSUE TITLE
[Bug] Wrong user profile information used on bridged messages

### ISSUE THREAD

**Issue by greeeen-dev** [UnifierHQ/unifier#185]
### Checklist

- [X] I've checked issues to see if my bug has been reported yet.
- [X] I'm reporting a Unifier software bug, not a user.
- [X] I've provided as much info/evidence as I can.

### Version

3.6.7

### Bug description

In some messages, Unifier will display the wrong user information when bridging messages. This has only happened for messages sent from Revolt so far. Sender information is somehow stored just fine in the message cache and reloading the bridge seems to temporarily fix the problem.

Possible causes:
- Bridge v3/NUPS is broken somewhere
- Revolt Support plugin is broken somewhere

Going to get all hands on deck to investigate this.

### Reproduction steps

1. Send a message from Revolt (or Guilded)

### Expected behavior

User profile appears properly for each message.

### Plugins

Revolt Support, Guilded Support

### Modified instance

- [ ] Yes, I'm running a modified version of Unifier.

**Comment by lezetho** [comment]
hmm yes yes i see i shall take a look at home

**Comment by greeeen-dev** [comment]
Decided to implement a new `UnifierUser` class for handling user names, avatars, etc. Hopefully this helps.

**Comment by greeeen-dev** [comment]
Closing this issue for now since I've created a possible patch but please do check my new code to see if the bug could happen again.
