### ISSUE TITLE
Cross-server reactions

### ISSUE THREAD

**Issue by greeeen-dev** [UnifierHQ/unifier#94]
**Checklist**

- [X] The same feedback was not posted yet.
- [X] This is not a suggestion for the moderation team.
- [X] All info applicable to the issue has been attached.

**Is your feature request related to a problem? Please describe.**

Reactions to messages are not being bridged over to other servers.

**Describe the solution you'd like**

Add a system to bridge reactions across all servers.

**Describe alternatives you've considered**

**Additional context**

Still unclear how reactions can be displayed. Suggestions are welcome.

**Comment by CrimsonFork** [comment]
It seems there has been a regression with this feature, as We don't see reactions being bridged between Discord and Revolt.

**Comment by greeeen-dev** [comment]
You need to use the View reactions button to view the reactions.
<img width="474" alt="Image" src="https://github.com/user-attachments/assets/de0703ff-88d9-4f87-82a5-2cf1de18e615" />
